services:
  bandu_db:
    image: postgres:15
    container_name: web_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: bandu_app_db
    volumes:
      - bandu_pgdata:/var/lib/postgresql/data
    networks:
      - bandu-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATASOURCE_USERNAME} -d bandu_app_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  bandu_app:
    build: .
    container_name: web_app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      bandu_db:
        condition: service_healthy
    networks:
      - bandu-network

  nginx:
    image: nginx:latest
    container_name: bandu_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Let's Encrypt
    depends_on:
      - bandu_app
    networks:
      - bandu-network

networks:
  bandu-network:
    driver: bridge

volumes:
  bandu_pgdata: