services:
  bandu_db:
    image: postgres:15
    container_name: web_db
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=${DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${JPA_DDL}
      - SPRING_JPA_SHOW_SQL=${JPA_SHOW_SQL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_TOKEN_LIFETIME_DAY=${JWT_TOKEN_LIFETIME_DAY}
    volumes:
      - bandu_pgdata:/var/lib/postgresql/data
    networks:
      - bandu-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATASOURCE_USERNAME} -d bandu_app_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  bandu_app:
    build: .
    container_name: web_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      bandu_db:
        condition: service_healthy
    networks:
      - bandu-network

networks:
  bandu-network:
    driver: bridge

volumes:
  bandu_pgdata: