services:
  zayrx_control_db:
    image: postgres:15
    container_name: zayrx_control_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: zayrx_control_db
    volumes:
      - zayrx_control_pgdata:/var/lib/postgresql/data
    networks:
      - zayrx-control-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATASOURCE_USERNAME} -d zayrx_control_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  zayrx_control_app:
    build: .
    container_name: zayrx_control_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:8080:8080"  # Faqat localhost dan, nginx orqali
    depends_on:
      zayrx_control_db:
        condition: service_healthy
    networks:
      - zayrx-control-network

networks:
  zayrx-control-network:
    driver: bridge

volumes:
  zayrx_control_pgdata: